name: Ubuntu
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - master

env:
  SCHEME: scheme

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IDRIS2_CG: chez
      IDRIS2_TESTS_CG: chez
    container: snazzybucket/idris2api:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build and test
        run: |
          make build && make test INTERACTIVE=''
        shell: bash
